package it.unito.iumtweb.springboot.studio;

import jakarta.persistence.*;

/**
 * Represents a Studio entity in the database.
 * This class is managed by JPA to map Studio objects to a relational database.
 */
@Entity
@Table
public class Studio {

    /**
     * The unique identifier for the Studio.
     * It is automatically generated by the database using an identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the studio.
     * This field is mandatory and cannot be null.
     */
    @Column(nullable = false)
    private String studio;

    /**
     * Default no-argument constructor.
     * Required by JPA for creating instances via reflection.
     */
    public Studio() {
        // Default constructor required by JPA
    }

    /**
     * Constructs a Studio with the specified attributes.
     *
     * @param id     The unique identifier of the Studio.
     * @param studio The name of the studio.
     */
    public Studio(Long id, String studio) {
        this.id = id;
        this.studio = studio;
    }

    /**
     * Retrieves the unique identifier of the Studio.
     *
     * @return The ID of the Studio.
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the Studio.
     *
     * @param id The ID to set for the Studio.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Retrieves the name of the studio.
     *
     * @return The name of the studio.
     */
    public String getStudio() {
        return studio;
    }

    /**
     * Sets the name of the studio.
     *
     * @param name The name to set for the Studio.
     */
    public void setStudio(String name) {
        this.studio = name;
    }
}
