package it.unito.iumtweb.springboot.crew;

import jakarta.persistence.*;

/**
 * Represents a Crew entity in the database.
 * This class is managed by JPA to map Crew objects to a relational database.
 */
@Entity
@Table
public class Crew {

    /**
     * The unique identifier for the Crew.
     * It is automatically generated by the database using an identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The role of the Crew member.
     * This field is mandatory and cannot be null.
     */
    @Column(nullable = false)
    private String role;

    /**
     * The name of the Crew member.
     * This field is optional.
     */
    @Column
    private String name;

    /**
     * Default no-argument constructor.
     * Required by JPA for creating instances via reflection.
     */
    public Crew() {
        // Default constructor required by JPA
    }

    /**
     * Constructs a Crew with the specified ID, role, and name.
     *
     * @param id   The unique identifier of the Crew.
     * @param role The role of the Crew member.
     * @param name The name of the Crew member.
     */
    public Crew(Long id, String role, String name) {
        this.id = id;
        this.role = role;
        this.name = name;
    }

    /**
     * Retrieves the unique identifier of the Crew.
     *
     * @return The ID of the Crew.
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the Crew.
     *
     * @param id The ID to set for the Crew.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Retrieves the role of the Crew member.
     *
     * @return The role of the Crew member.
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the role of the Crew member.
     *
     * @param role The role to set for the Crew member.
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * Retrieves the name of the Crew member.
     *
     * @return The name of the Crew member.
     */
    public String getName() { return name; }

    /**
     * Sets the name of the Crew member.
     *
     * @param name The name to set for the Crew member.
     */
    public void setName(String name) {
        this.name = name;
    }
}
