package it.unito.iumtweb.springboot.poster;

import jakarta.persistence.*;

/**
 * Represents a Poster entity in the database.
 * This class is managed by JPA to map Poster objects to a relational database.
 */
@Entity
@Table
public class Poster {

    /**
     * The unique identifier for the Poster.
     * It is automatically generated by the database using an identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The link to the poster image or resource.
     * This field is mandatory and cannot be null.
     */
    @Column(nullable = false)
    private String link;

    /**
     * Default no-argument constructor.
     * Required by JPA for creating instances via reflection.
     */
    public Poster() {
        // Default constructor required by JPA
    }

    /**
     * Constructs a Poster with the specified attributes.
     *
     * @param id   The unique identifier of the Poster.
     * @param link The link to the poster image or resource.
     */
    public Poster(Long id, String link) {
        this.id = id;
        this.link = link;
    }

    /**
     * Retrieves the unique identifier of the Poster.
     *
     * @return The ID of the Poster.
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the Poster.
     *
     * @param id The ID to set for the Poster.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Retrieves the link to the poster image or resource.
     *
     * @return The link to the poster.
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the link to the poster image or resource.
     *
     * @param link The link to set for the Poster.
     */
    public void setLink(String link) {
        this.link = link;
    }
}
