package it.unito.iumtweb.springboot.genre;

import jakarta.persistence.*;

/**
 * Represents a Genre entity in the database.
 * This class is managed by JPA to map Genre objects to a relational database.
 */
@Entity
@Table
public class Genre {

    /**
     * The unique identifier for the Genre.
     * It is automatically generated by the database using an identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The name of the Genre.
     * This field is mandatory and cannot be null.
     */
    @Column(nullable = false)
    private String genre;

    /**
     * Default no-argument constructor.
     * Required by JPA for creating instances via reflection.
     */
    public Genre() {
        // Default constructor required by JPA
    }

    /**
     * Constructs a Genre with the specified ID and name.
     *
     * @param id    The unique identifier of the Genre.
     * @param genre The name of the Genre.
     */
    public Genre(Long id, String genre) {
        this.id = id;
        this.genre = genre;
    }

    /**
     * Gets the unique identifier of the Genre.
     *
     * @return The ID of the Genre.
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the Genre.
     *
     * @param id The ID to set for the Genre.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the name of the Genre.
     *
     * @return The name of the Genre.
     */
    public String getGenre() {
        return genre;
    }

    /**
     * Sets the name of the Genre.
     *
     * @param name The name to set for the Genre.
     */
    public void setGenre(String name) {
        this.genre = name;
    }
}
