package it.unito.iumtweb.springboot.release;

import jakarta.persistence.*;

import java.sql.Date;

/**
 * Represents a Release entity in the database.
 * This class is managed by JPA to map Release objects to a relational database.
 */
@Entity
@Table
public class Release {

    /**
     * The unique identifier for the Release.
     * It is automatically generated by the database using an identity strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The country where the release occurred.
     * This field is mandatory and cannot be null.
     */
    @Column(nullable = false)
    private String country;

    /**
     * The release date.
     * This field is optional and can be null.
     */
    @Column
    private Date date;

    /**
     * The type of release (e.g., "theatrical", "digital").
     * This field is optional and can be null.
     */
    @Column
    private String type;

    /**
     * The rating associated with the release (e.g., "PG-13", "R").
     * This field is optional and can be null.
     */
    @Column
    private String rating;

    /**
     * Default no-argument constructor.
     * Required by JPA for creating instances via reflection.
     */
    public Release() {
        // Default constructor required by JPA
    }

    /**
     * Constructs a Release with the specified attributes.
     *
     * @param id      The unique identifier of the Release.
     * @param country The country where the release occurred.
     * @param date    The release date.
     * @param type    The type of release.
     * @param rating  The rating associated with the release.
     */
    public Release(Long id, String country, Date date, String type, String rating) {
        this.id = id;
        this.country = country;
        this.date = date;
        this.type = type;
        this.rating = rating;
    }

    /**
     * Retrieves the unique identifier of the Release.
     *
     * @return The ID of the Release.
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the Release.
     *
     * @param id The ID to set for the Release.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Retrieves the country where the release occurred.
     *
     * @return The country of the Release.
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the country where the release occurred.
     *
     * @param country The country to set for the Release.
     */
    public void setCountry(String name) {
        this.country = name;
    }

    /**
     * Retrieves the release date.
     *
     * @return The date of the Release.
     */
    public Date getDate() {
        return date;
    }

    /**
     * Sets the release date.
     *
     * @param date The date to set for the Release.
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * Retrieves the type of release.
     *
     * @return The type of the Release.
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the type of release.
     *
     * @param type The type to set for the Release.
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Retrieves the rating associated with the release.
     *
     * @return The rating of the Release.
     */
    public String getRating() {
        return rating;
    }

    /**
     * Sets the rating associated with the release.
     *
     * @param rating The rating to set for the Release.
     */
    public void setRating(String rating) {
        this.rating = rating;
    }
}
